### ISSUE TITLE
Sendable conformance

### ISSUE THREAD

**Issue by mcomisso** [liamnichols/xcstrings-tool#40] opened 2024-01-12 23:17 UTC
Thanks for open sourcing this!

Using it on some parts marked `@MainActor`. Xcode produces the following warnings:

```
Passing argument of non-sendable type 'LocalizedStringResource' outside of main actor-isolated context may introduce data races
```

Being static strings I think we should be able to make it @Sendable? 🤔

**Comment by liamnichols** [comment] 2024-01-13 08:49
Interesting! I haven’t used Swift Concurrency much myself yet so I’m not so familiar in this area, but I think that you are right. 

Is this a case of me having to add `Sendable` conformance to the nested `LocalizedStringResource.Localizable` struct? The error seems to suggest that it’s an issue with `LocalizedStringResource`, but that’s a Foundation type and I don’t think I can add sendable directly to that?

**Comment by liamnichols** [comment] 2024-01-24 18:04
An Apple Frameworks Engineer specifies that `LocalizedStringResource` cannot be made `Sendable` 😕 

https://forums.developer.apple.com/forums/thread/732362

Unfortunately I don't think that we can do anything about this from our side. I guess that you might need to load the resource into a `String` before passing it across isolation domains? 

I'm going to close this issue for now, but please reopen it if you feel that there is something that can be done here. Thanks!

**Comment by mcomisso** [comment] 2024-01-24 18:13
Thank you for looking into this! And apologies for not replying the last few days.

That's a very interesting find! 
I don't have enough experience on the subject, but I guess if not `@Sendable` the improvement could be to make it `@MainActor` to require the `await` when interacted in an unsafe context? 🤔

**Comment by liamnichols** [comment] 2024-01-24 18:28
> I don't have enough experience on the subject, but I guess if not @Sendable the improvement could be to make it @MainActor to require the await when interacted in an unsafe context? 🤔

Me neither 😄 Maybe I should leave this open a bit longer then.. 

Would it be possible for you to share a code example that surfaces the issue that you are describing? I'm not quite sure how to reproduce the warning that you are seeing.

**Comment by mcomisso** [comment] 2024-01-24 22:13
Sure, writing it by memory, but if I'm not wrong was something like this:

```swift

struct SomeView: View {
  var body: some View {
    myVarView
  }

  @MainActor
  @ViewBuilder
  var myVarView: some View {
    Text(.localizable.footerText(items.count))  // <- warning
  }
}
```

**Comment by liamnichols** [comment] 2024-02-08 20:14
Sorry for the delay, but I tried replicating this in the demo app and I can't seem to reproduce the warning that you described.

If you get some time, please can you share a project that replicates the issue? Using the [demo project](https://github.com/liamnichols/xcstrings-tool-demo) might help if you can't share your own source code

**Comment by liamnichols** [comment] 2024-04-03 05:59
When I opened the demo project in Xcode **15.3**, I see this warning in the generated code:

<img width="1326" alt="Screenshot 2024-04-03 at 07 57 34" src="https://github.com/liamnichols/xcstrings-tool/assets/482871/1cca64a3-73fe-4ef2-a6b7-007e72e0e595">

Seems to be related.. Will look into it.

**Closed** 2024-05-28 15:50 UTC
Labels: enhancement
